In [1]:
import pandas as pd

# Reading Data

In [2]:
df =pd.read_csv('data.csv')

In [3]:
df.head()

fever  bodyPain  age  runnyNoise  diffBreath  infectionProb
0   98.472066         0   51           1          -1              1
1   99.293711         1   31           1           0              0
2   99.326865         0   47           1           1              0
3  100.445907         1   14           1          -1              1
4  101.637440         1   95           1           0              1

In [4]:
df.tail()

fever  bodyPain  age  runnyNoise  diffBreath  infectionProb
3787   99.739856         1   24           1           1              1
3788   98.437126         1   64           0          -1              0
3789  100.953137         1   99           0           0              0
3790  100.384806         0   16           1           1              1
3791  101.241095         0   38           1           1              1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3792 entries, 0 to 3791
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   fever          3792 non-null   float64
 1   bodyPain       3792 non-null   int64  
 2   age            3792 non-null   int64  
 3   runnyNoise     3792 non-null   int64  
 4   diffBreath     3792 non-null   int64  
 5   infectionProb  3792 non-null   int64  
dtypes: float64(1), int64(5)
memory usage: 177.8 KB


In [6]:
df['diffBreath'].value_counts()

 1    1272
 0    1261
-1    1259
Name: diffBreath, dtype: int64

In [7]:
df.describe()

fever     bodyPain          age   runnyNoise   diffBreath  \
count  3792.000000  3792.000000  3792.000000  3792.000000  3792.000000   
mean    100.019819     0.505538    50.051951     0.495253     0.003428   
std       1.155536     0.500035    28.764962     0.500043     0.817081   
min      98.000044     0.000000     1.000000     0.000000    -1.000000   
25%      98.993455     0.000000    26.000000     0.000000    -1.000000   
50%     100.039891     1.000000    50.000000     0.000000     0.000000   
75%     101.010736     1.000000    75.000000     1.000000     1.000000   
max     101.995956     1.000000   100.000000     1.000000     1.000000   

       infectionProb  
count    3792.000000  
mean        0.512922  
std         0.499899  
min         0.000000  
25%         0.000000  
50%         1.000000  
75%         1.000000  
max         1.000000

## Train Test Spliting

In [8]:
import numpy as np

In [9]:
# shuffled = np.random.permutation(7)
# shuffled
# x = shuffled[:3]
# x
# y =shuffled[3:]
# y
# example to see the slipt function
def data_split(data,ratio):
    np.random.seed(42)
    shuffled =np.random.permutation(len(data))
    test_set_size = int(len(data)*ratio)
    test_indices = shuffled[:test_set_size]
    train_indices = shuffled[test_set_size:]
    return data.iloc[train_indices], data.iloc[test_indices]
    

In [10]:
train,test =data_split(df,0.2)

In [11]:
train

fever  bodyPain  age  runnyNoise  diffBreath  infectionProb
1220  100.791428         1   96           1           0              0
3365   98.902124         0   33           1          -1              1
3266  101.789541         1   97           0           1              1
1436  101.096447         1   20           1           1              1
937    98.939529         1   22           1           0              0
...          ...       ...  ...         ...         ...            ...
1130  101.248106         1   82           0           0              1
1294   98.929702         0   35           1          -1              1
860   101.432291         0   36           0           1              0
3507  100.934524         1   96           0          -1              0
3174   98.065458         0   34           1          -1              1

[3034 rows x 6 columns]

In [12]:
test

fever  bodyPain  age  runnyNoise  diffBreath  infectionProb
1582   98.997398         0   56           0           1              1
3538  101.716507         1   78           0           1              1
263    98.437068         1   73           0           0              1
2474   98.442693         0   62           0           1              0
3140  101.109732         1   62           0           0              1
...          ...       ...  ...         ...         ...            ...
246   100.202264         1   27           1          -1              1
1221  100.137323         1    2           1          -1              0
734    99.987171         1   43           1           1              0
505    99.470803         1   41           0           1              1
3583  100.271807         1   93           0           1              1

[758 rows x 6 columns]

In [13]:
X_train = train[['fever','bodyPain','age','runnyNoise','diffBreath']].to_numpy()
X_test = test[['fever','bodyPain','age','runnyNoise','diffBreath']].to_numpy()

In [14]:
X_train

array([[100.7914283 ,   1.        ,  96.        ,   1.        ,
          0.        ],
       [ 98.90212423,   0.        ,  33.        ,   1.        ,
         -1.        ],
       [101.7895405 ,   1.        ,  97.        ,   0.        ,
          1.        ],
       ...,
       [101.4322907 ,   0.        ,  36.        ,   0.        ,
          1.        ],
       [100.9345238 ,   1.        ,  96.        ,   0.        ,
         -1.        ],
       [ 98.06545798,   0.        ,  34.        ,   1.        ,
         -1.        ]])

In [15]:
X_test

array([[ 98.99739771,   0.        ,  56.        ,   0.        ,
          1.        ],
       [101.7165075 ,   1.        ,  78.        ,   0.        ,
          1.        ],
       [ 98.43706818,   1.        ,  73.        ,   0.        ,
          0.        ],
       ...,
       [ 99.98717082,   1.        ,  43.        ,   1.        ,
          1.        ],
       [ 99.47080347,   1.        ,  41.        ,   0.        ,
          1.        ],
       [100.2718075 ,   1.        ,  93.        ,   0.        ,
          1.        ]])

In [16]:
Y_train = train[['infectionProb']].to_numpy().reshape(3034,)
Y_test = test[['infectionProb']].to_numpy().reshape(758,)

In [17]:
Y_train

array([0, 1, 1, ..., 0, 0, 1], dtype=int64)

## From sklearn we train model using Linear regression method

In [18]:
from sklearn.linear_model import LogisticRegression

In [19]:
clf =LogisticRegression()

In [20]:
clf.fit(X_train,Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [21]:
inputFeatures = [100,1,30,0,1]
infProb = clf.predict_proba([inputFeatures])[0][1]

In [22]:
infProb

0.5494745785731258